# Generated by Django 4.1.1 on 2022-09-18 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[('1', 'King'), ('2', 'Queen'), ('3', 'Rook'), ('4', 'Bishop'), ('5', 'Knight'), ('6', 'Pawn')])),
                ('color', models.IntegerField(choices=[('1', 'Black'), ('2', 'White')])),
            ],
            options={
                'verbose_name': 'Piece',
                'db_table': 'piece',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPiece',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('type', models.IntegerField(choices=[('1', 'King'), ('2', 'Queen'), ('3', 'Rook'), ('4', 'Bishop'), ('5', 'Knight'), ('6', 'Pawn')])),
                ('color', models.IntegerField(choices=[('1', 'Black'), ('2', 'White')])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Piece',
                'verbose_name_plural': 'historical Pieces',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
