name: chessboard

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo All test has been passed

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Build
        run: echo Build finished
  
  deploy-prod:
    runs-on: ubuntu-latest
    branches:
      main
    environment:
      name: production
      url: ''
    needs: build
    steps:
      - name: Deploy production environment
        run: echo Deployment finished
